'use server'

import { db } from '@/db'
import { decks, flashcards } from '@/db/schema'
import { getSession } from '@/lib/auth'
import { eq, and } from 'drizzle-orm'
import { redirect } from 'next/navigation'
import { z } from 'zod'
import { revalidatePath } from 'next/cache'

const createDeckSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  description: z.string().optional(),
  topic: z.string().min(1, 'Topic is required'),
})

export async function createDeck(formData: FormData) {
  const session = await getSession()
  if (!session) {
    redirect('/signin')
  }

  const rawData = {
    title: formData.get('title'),
    description: formData.get('description'),
    topic: formData.get('topic'),
  }

  const result = createDeckSchema.safeParse(rawData)
  if (!result.success) {
    return { error: result.error.errors[0].message }
  }

  const { title, description, topic } = result.data

  const [newDeck] = await db.insert(decks).values({
    userId: session.userId,
    title,
    description: description || null,
    topic,
  }).returning()

  revalidatePath('/dashboard')
  return { success: true, deckId: newDeck.id }
}

export async function deleteDeck(deckId: number) {
  const session = await getSession()
  if (!session) {
    redirect('/signin')
  }

  await db.delete(decks).where(
    and(
      eq(decks.id, deckId),
      eq(decks.userId, session.userId)
    )
  )

  revalidatePath('/dashboard')
  return { success: true }
}

export async function getUserDecks() {
  const session = await getSession()
  if (!session) {
    redirect('/signin')
  }

  const userDecks = await db.query.decks.findMany({
    where: eq(decks.userId, session.userId),
    orderBy: (decks, { desc }) => [desc(decks.createdAt)],
    with: {
      flashcards: true,
    },
  })

  return userDecks
}

export async function getDeckWithCards(deckId: number) {
  const session = await getSession()
  if (!session) {
    redirect('/signin')
  }

  const deck = await db.query.decks.findFirst({
    where: and(
      eq(decks.id, deckId),
      eq(decks.userId, session.userId)
    ),
    with: {
      flashcards: true,
    },
  })

  if (!deck) {
    return null
  }

  return deck
}

// Placeholder for AI card generation - you'll integrate Vercel AI SDK here
export async function generateFlashcards(deckId: number, topic: string, count: number = 10) {
  const session = await getSession()
  if (!session) {
    redirect('/signin')
  }

  // TODO: Integrate with Vercel AI SDK to generate flashcards
  // For now, create placeholder cards
  const placeholderCards = Array.from({ length: count }, (_, i) => ({
    deckId,
    question: `Sample question ${i + 1} about ${topic}`,
    answer: `Sample answer ${i + 1} - This will be generated by AI`,
  }))

  await db.insert(flashcards).values(placeholderCards)

  revalidatePath(`/dashboard/deck/${deckId}`)
  return { success: true, count }
}
